target/i386: tcg stubs
missing since 55c3ceef61:

    LINK    x86_64-softmmu/qemu-system-x86_64
  target/i386/cpu.o: In function `x86_cpu_common_class_init':
  target/i386/cpu.c:4215: undefined reference to `tcg_x86_init'

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>