hw/misc/cpc: Include missing 'hw/core/cpu.h' header
The "hw/core/cpu.h" header is indirectly included. Include it
explicitly otherwise we get when refactoring unrelated headers:

  ../hw/misc/mips_cpc.c:36:53: error: unknown type name 'run_on_cpu_data'
     36 | static void mips_cpu_reset_async_work(CPUState *cs, run_on_cpu_data data)
        |                                                     ^
  ../hw/misc/mips_cpc.c:40:5: error: call to undeclared function 'cpu_reset'
       40 |     cpu_reset(cs);
          |     ^
  ../hw/misc/riscv_cpc.c:34:54: error: unknown type name 'run_on_cpu_data'
     34 | static void riscv_cpu_reset_async_work(CPUState *cs, run_on_cpu_data data)
        |                                                      ^
  ../hw/misc/riscv_cpc.c:39:5: error: call to undeclared function 'cpu_reset'
     39 |     cpu_reset(cs);
        |     ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>