remote-port-proto: avoid to redefine _DEFAULT_SOURCE
Since it might already be defined (since cf2b224e501)

  $ gcc -v
  gcc version 7.2.0 (Debian 7.2.0-14)
  $ make
    CC      aarch64-softmmu/hw/core/remote-port-proto.o
  hw/core/remote-port-proto.c:26:0: error: "_DEFAULT_SOURCE" redefined [-Werror]
  make[1]: *** [hw/core/remote-port-proto.o] Error 1

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>