missing include
In file included from /home/phil/source/qemu/hw/display/vga_int.h:28,
                 from /home/phil/source/qemu/hw/display/vga-vbe-unaligned.c:25:
/home/phil/source/qemu/include/exec/ioport.h:42:14: error: unknown type name ‘MemoryRegionOps’
 extern const MemoryRegionOps unassigned_io_ops;
              ^~~~~~~~~~~~~~~
/home/phil/source/qemu/include/exec/ioport.h:54:5: error: unknown type name ‘Object’
     Object *owner;
     ^~~~~~
/home/phil/source/qemu/include/exec/ioport.h:63:44: error: unknown type name ‘Object’; did you mean ‘QObject’?
 void portio_list_init(PortioList *piolist, Object *owner,
                                            ^~~~~~
                                            QObject

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>