util/cacheinfo: add missing include
This include was forgotten when splitting cacheinfo.c out of
tcg/ppc/tcg-target.inc.c (see commit b255b2c8).

While compiling on powerpc:

      CC      util/cacheinfo.o
    qemu/util/cacheinfo.c: In function 'arch_cache_info':
    qemu/util/cacheinfo.c:137:33: error: 'AT_ICACHEBSIZE' undeclared (first use in this function)
             *isize = qemu_getauxval(AT_ICACHEBSIZE);
                                     ^
    qemu/util/cacheinfo.c:137:33: note: each undeclared identifier is reported only once for each function it appears in
    qemu/util/cacheinfo.c:140:33: error: 'AT_DCACHEBSIZE' undeclared (first use in this function)
             *dsize = qemu_getauxval(AT_DCACHEBSIZE);
                                     ^
    qemu/rules.mak:66: recipe for target 'util/cacheinfo.o' failed
    make: *** [util/cacheinfo.o] Error 1

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>