hw/i386: Allow building machines without IOMMU
Commit 6c730e4af9 introduced a stub to build the MicroVM machine
without Intel IOMMU suppport. However when configure with
--without-default-devices, the build fails:

    LINK    x86_64-softmmu/qemu-system-x86_64
  /usr/bin/ld: hw/i386/pc.o: in function `pc_machine_done':
  hw/i386/pc.c:869: undefined reference to `x86_iommu_ir_supported'
  /usr/bin/ld: hw/i386/acpi-build.o: in function `acpi_build':
  hw/i386/acpi-build.c:2844: undefined reference to `x86_iommu_get_type'
  /usr/bin/ld: hw/i386/acpi-build.o: in function `build_dmar_q35':
  hw/i386/acpi-build.c:2478: undefined reference to `x86_iommu_ir_supported'
  /usr/bin/ld: hw/i386/acpi-build.o: in function `build_amd_iommu':
  hw/i386/acpi-build.c:2665: undefined reference to `x86_iommu_ir_supported'
  /usr/bin/ld: hw/i386/acpi-build.c:2700: undefined reference to `x86_iommu_ir_supported'
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:206: qemu-system-x86_64] Error 1

Since currently all PC machines can not be built without IOMMU,
select X86_IOMMU in the PC config, and remove the stubs.

Fixes: 6c730e4af9
Reported-by: Travis-CI
Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
---
v2: simplify, remove the stub.