missing inc
In file included from /home/phil/source/qemu/hw/display/vga-vbe-unaligned.c:25:
/home/phil/source/qemu/hw/display/vga_int.h:172:14: error: unknown type name ‘VMStateDescription’
 extern const VMStateDescription vmstate_vga_common;
              ^~~~~~~~~~~~~~~~~~
make[1]: *** [/home/phil/source/qemu/rules.mak:69: hw/display/vga-vbe-unaligned.o] Error 1