tests: Let Fedora build with OpenGL
Include packages required to build with OpenGL, as suggested:

  $ ./configure --enable-opengl

  ERROR: User requested feature opengl
         configure was not able to find it.
         Please install opengl (mesa) devel pkgs: epoxy gbm

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>