sd: add missing break in sd_set_voltage()
    hw/sd/sd.c: In function ‘sd_set_voltage’:
    hw/sd/sd.c:155:12: error: this statement may fall through [-Werror=implicit-fallthrough=]
         if (!sd->uhs) {
            ^
    hw/sd/sd.c:162:5: note: here
         default:
         ^~~~~~~
    make: *** [hw/sd/sd.o] Error 1

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>