accel/tcg: add missing target-independent stubs
missing since 44eff67341:

    LINK    x86_64-softmmu/qemu-system-x86_64
  exec.o: In function `tlb_reset_dirty_range_all':
  exec.c:1070: undefined reference to `tlb_reset_dirty'
  exec.o: In function `tcg_commit':
  exec.c:2704: undefined reference to `cpu_reloading_memory_map'
  cpus.o: In function `tcg_cpu_exec':
  cpus.c:1270: undefined reference to `cpu_exec'
  cpus.o: In function `qemu_tcg_rr_cpu_thread_fn':
  cpus.c:1374: undefined reference to `cpu_exec_step_atomic'
  cpus.o: In function `qemu_tcg_cpu_thread_fn':
  cpus.c:1490: undefined reference to `cpu_exec_step_atomic'
  cpus.o: In function `qemu_tcg_init_vcpu':
  cpus.c:1675: undefined reference to `parallel_cpus'
  collect2: error: ld returned 1 exit status
  Makefile:197: recipe for target 'qemu-system-x86_64' failed

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>