accel/tcg: add a stub for tcg_register_thread()
missing since 3468b59e18:

    LINK    x86_64-softmmu/qemu-system-x86_64
  cpus.o: In function `qemu_tcg_rr_cpu_thread_fn':
  cpus.c:1310: undefined reference to `tcg_register_thread'
  cpus.o: In function `qemu_tcg_cpu_thread_fn':
  cpus.c:1458: undefined reference to `tcg_register_thread'

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>