Revert "pc: stubify x86 iommu"
  LINK    x86_64-softmmu/qemu-system-x86_64
/usr/bin/ld: hw/i386/pc.o: in function `pc_machine_done':
/home/phil/source/qemu/hw/i386/pc.c:869: undefined reference to `x86_iommu_ir_supported'
/usr/bin/ld: hw/i386/acpi-build.o: in function `acpi_build':
/home/phil/source/qemu/hw/i386/acpi-build.c:2844: undefined reference to `x86_iommu_get_type'
/usr/bin/ld: hw/i386/acpi-build.o: in function `build_dmar_q35':
/home/phil/source/qemu/hw/i386/acpi-build.c:2478: undefined reference to `x86_iommu_ir_supported'
/usr/bin/ld: hw/i386/acpi-build.o: in function `build_amd_iommu':
/home/phil/source/qemu/hw/i386/acpi-build.c:2665: undefined reference to `x86_iommu_ir_supported'
/usr/bin/ld: /home/phil/source/qemu/hw/i386/acpi-build.c:2700: undefined reference to `x86_iommu_ir_supported'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:206: qemu-system-x86_64] Error 1

This reverts commit 6c730e4af9b64b6c83b233f285ec3649747f7eda.

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>