exec: shadow
commit 077874e01fd

/home/phil/source/qemu/exec.c: In function ‘cpu_physical_memory_snapshot_and_clear_dirty’:
/home/phil/source/qemu/exec.c:1421:23: error: declaration of ‘offset’ shadows a parameter [-Werror=shadow=compatible-local]
 1421 |         unsigned long offset = page % DIRTY_MEMORY_BLOCK_SIZE;
      |                       ^~~~~~
/home/phil/source/qemu/exec.c:1396:31: note: shadowed declaration is here
 1396 |     (MemoryRegion *mr, hwaddr offset, hwaddr length, unsigned client)
      |                        ~~~~~~~^~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>